import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./ThemeProvider";
import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <NavBar />
        <body
          className={`${inter.className} font-sans bg-bgColor relative pt-[100px] dark:bg-darkBgColor`}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
